### ISSUE TITLE
Github Organization 作成及びRepository移管、権限整理

### ISSUE THREAD

**Issue by tooget** [wk-since-2021/Six-Codes-Mutual-Link-PJ#2]
@u-hir Github Organizationにしてみませんか？ レポジトリやアカウントの権限管理が容易くなるようです
 - https://docs.github.com/ja/organizations/collaborating-with-groups-in-organizations/creating-a-new-organization-from-scratch
 - https://qiita.com/chari/items/ee16bf16715f4bbcbd9b

**Comment by u-hir** [comment]
GitHubOrganizationというのは初めて聞いたので調べてみます

**Comment by tooget** [comment]
https://github.com/wk-since-2021

作られてOrganizationの組織として管理できるようになりました。
